name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Starter Docker Test
        uses: cubetiq/starter-docker-actions@v0.6
        with:
          shell: bash
          run: docker version
